// All 36 Maharashtra Districts
export const DISTRICTS = [
  'Ahmednagar',
  'Akola',
  'Amravati',
  'Aurangabad',
  'Beed',
  'Bhandara',
  'Buldhana',
  'Chandrapur',
  'Dhule',
  'Gadchiroli',
  'Gondia',
  'Hingoli',
  'Jalgaon',
  'Jalna',
  'Kolhapur',
  'Latur',
  'Mumbai City',
  'Mumbai Suburban',
  'Nagpur',
  'Nanded',
  'Nandurbar',
  'Nashik',
  'Osmanabad',
  'Palghar',
  'Parbhani',
  'Pune',
  'Raigad',
  'Ratnagiri',
  'Sangli',
  'Satara',
  'Sindhudurg',
  'Solapur',
  'Thane',
  'Wardha',
  'Washim',
  'Yavatmal',
];

// Comprehensive Talukas by District - All 36 Districts
export const TALUKAS: Record<string, string[]> = {
  'Ahmednagar': ['Ahmednagar', 'Akole', 'Jamkhed', 'Karjat', 'Kopargaon', 'Nagar', 'Nevasa', 'Parner', 'Pathardi', 'Rahata', 'Rahuri', 'Sangamner', 'Shevgaon', 'Shrigonda', 'Shrirampur'],
  'Akola': ['Akola', 'Akot', 'Balapur', 'Barshitakli', 'Murtizapur', 'Patur', 'Telhara'],
  'Amravati': ['Achalpur', 'Amravati', 'Anjangaon Surji', 'Bhatkuli', 'Chandur Railway', 'Chandurbazar', 'Daryapur', 'Dharni', 'Dhamangaon Railway', 'Morshi', 'Nandgaon Khandeshwar', 'Teosa', 'Warud', 'Chikhaldara'],
  'Aurangabad': ['Aurangabad', 'Gangapur', 'Kannad', 'Khuldabad', 'Paithan', 'Phulambri', 'Sillod', 'Soegaon', 'Vaijapur'],
  'Beed': ['Ambajogai', 'Ashti', 'Beed', 'Dharur', 'Georai', 'Kaij', 'Majalgaon', 'Parli', 'Patoda', 'Shirur Kasar', 'Wadwani'],
  'Bhandara': ['Bhandara', 'Lakhani', 'Mohadi', 'Pauni', 'Sakoli', 'Tumsar'],
  'Buldhana': ['Buldana', 'Chikhli', 'Deulgaon Raja', 'Jalgaon Jamod', 'Khamgaon', 'Lonar', 'Malkapur', 'Mehkar', 'Motala', 'Nandura', 'Sangrampur', 'Shegaon', 'Sindkhed Raja'],
  'Chandrapur': ['Ballarpur', 'Bhadravati', 'Bramhapuri', 'Chandrapur', 'Chimur', 'Gondpipri', 'Jivati', 'Korpana', 'Mul', 'Nagbhir', 'Pombhurna', 'Rajura', 'Saoli', 'Sindewahi', 'Warora'],
  'Dhule': ['Dhule', 'Sakri', 'Shirpur', 'Sindkheda'],
  'Gadchiroli': ['Aheri', 'Armori', 'Bhamragad', 'Chamorshi', 'Desaiganj', 'Dhanora', 'Etapalli', 'Gadchiroli', 'Korchi', 'Kurkheda', 'Mulchera', 'Sironcha'],
  'Gondia': ['Amgaon', 'Arjuni Morgaon', 'Deori', 'Goregaon', 'Gondia', 'Sadak Arjuni', 'Salekasa', 'Tirora'],
  'Hingoli': ['Aundha Nagnath', 'Basmath', 'Hingoli', 'Kalamnuri', 'Sengaon'],
  'Jalgaon': ['Amalner', 'Bhadgaon', 'Bhusawal', 'Bodwad', 'Chalisgaon', 'Chopda', 'Dharangaon', 'Erandol', 'Jalgaon', 'Jamner', 'Muktainagar', 'Pachora', 'Parola', 'Raver', 'Yawal'],
  'Jalna': ['Ambad', 'Badnapur', 'Bhokardan', 'Ghansawangi', 'Jafferabad', 'Jalna', 'Mantha', 'Partur'],
  'Kolhapur': ['Ajra', 'Bavda', 'Bhudargad', 'Chandgad', 'Gadhinglaj', 'Hatkanangle', 'Kagal', 'Karvir', 'Panhala', 'Radhanagari', 'Shahuwadi', 'Shirol'],
  'Latur': ['Ahmadpur', 'Ausa', 'Chakur', 'Deoni', 'Jalkot', 'Latur', 'Nilanga', 'Renapur', 'Shirur Anantpal', 'Udgir'],
  'Mumbai City': ['Mumbai City'],
  'Mumbai Suburban': ['Andheri', 'Borivali', 'Kurla'],
  'Nagpur': ['Bhiwapur', 'Hingna', 'Kalameshwar', 'Kamptee', 'Katol', 'Kuhi', 'Mauda', 'Nagpur Rural', 'Nagpur Urban', 'Narkhed', 'Parseoni', 'Ramtek', 'Savner', 'Umred'],
  'Nanded': ['Ardhapur', 'Bhokar', 'Biloli', 'Deglur', 'Dharmabad', 'Hadgaon', 'Himayatnagar', 'Kandhar', 'Kinwat', 'Loha', 'Mahur', 'Mudkhed', 'Mukhed', 'Naigaon', 'Nanded', 'Umri'],
  'Nandurbar': ['Akkalkuwa', 'Akrani', 'Nandurbar', 'Nawapur', 'Shahada', 'Taloda'],
  'Nashik': ['Baglan', 'Chandwad', 'Deola', 'Dindori', 'Igatpuri', 'Kalwan', 'Malegaon', 'Nandgaon', 'Nashik', 'Niphad', 'Peint', 'Sinnar', 'Surgana', 'Trimbakeshwar', 'Yeola'],
  'Osmanabad': ['Bhum', 'Kalamb', 'Lohara', 'Osmanabad', 'Paranda', 'Tuljapur', 'Umarga', 'Washi'],
  'Palghar': ['Dahanu', 'Jawhar', 'Mokhada', 'Palghar', 'Talasari', 'Vasai', 'Vikramgad', 'Wada'],
  'Parbhani': ['Gangakhed', 'Jintur', 'Manwath', 'Palam', 'Parbhani', 'Pathri', 'Purna', 'Sailu', 'Sonpeth'],
  'Pune': ['Ambegaon', 'Baramati', 'Bhor', 'Daund', 'Haveli', 'Indapur', 'Junnar', 'Khed', 'Mawal', 'Mulshi', 'Pune City', 'Purandhar', 'Shirur', 'Velhe'],
  'Raigad': ['Alibag', 'Karjat', 'Khalapur', 'Mahad', 'Mangaon', 'Mhasla', 'Murud', 'Panvel', 'Pen', 'Poladpur', 'Roha', 'Shrivardhan', 'Sudhagad', 'Tala', 'Uran'],
  'Ratnagiri': ['Chiplun', 'Dapoli', 'Guhagar', 'Khed', 'Lanja', 'Mandangad', 'Rajapur', 'Ratnagiri', 'Sangameshwar'],
  'Sangli': ['Atpadi', 'Jat', 'Kadegaon', 'Kavathemahankal', 'Khanapur', 'Miraj', 'Palus', 'Shirala', 'Tasgaon', 'Walwa'],
  'Satara': ['Jaoli', 'Karad', 'Khandala', 'Khatav', 'Koregaon', 'Mahabaleshwar', 'Man', 'Patan', 'Phaltan', 'Satara', 'Wai'],
  'Sindhudurg': ['Devgad', 'Dodamarg', 'Kankavli', 'Kudal', 'Malwan', 'Sawantwadi', 'Vaibhavwadi', 'Vengurla'],
  'Solapur': ['Akkalkot', 'Barshi', 'Karmala', 'Madha', 'Malshiras', 'Mangalvedhe', 'Mohol', 'Pandharpur', 'Sangole', 'Solapur North', 'Solapur South'],
  'Thane': ['Ambarnath', 'Bhiwandi', 'Kalyan', 'Murbad', 'Shahapur', 'Thane', 'Ulhasnagar'],
  'Wardha': ['Arvi', 'Ashti', 'Deoli', 'Hinganghat', 'Karanja', 'Samudrapur', 'Seloo', 'Wardha'],
  'Washim': ['Karanja', 'Malegaon', 'Mangrulpir', 'Manora', 'Risod', 'Washim'],
  'Yavatmal': ['Arni', 'Babulgaon', 'Darwha', 'Digras', 'Ghatanji', 'Kalamb', 'Kelapur', 'Mahagaon', 'Maregaon', 'Ner', 'Pusad', 'Ralegaon', 'Umarkhed', 'Wani', 'Yavatmal', 'Zari Jamani'],
};

// Comprehensive Crop List - Only actual crop names without category labels
export const CROPS = [
  'Groundnut',
  'Soybean',
  'Sunflower',
  'Safflower',
  'Sesame',
  'Niger',
  'Linseed',
  'Castor',
  'Rice',
  'Wheat',
  'Jowar (Sorghum)',
  'Bajra (Pearl Millet)',
  'Maize',
  'Ragi (Finger Millet)',
  'Barley',
  'Tur (Pigeon Pea)',
  'Gram (Chickpea)',
  'Moong (Green Gram)',
  'Urad (Black Gram)',
  'Masoor (Lentil)',
  'Kulthi (Horse Gram)',
  'Matki (Moth Bean)',
  'Onion',
  'Potato',
  'Tomato',
  'Brinjal (Eggplant)',
  'Cabbage',
  'Cauliflower',
  'Okra (Bhindi)',
  'Chilli',
  'Cucumber',
  'Bitter Gourd',
  'Bottle Gourd',
  'Pumpkin',
  'Beans',
  'Peas',
  'Carrot',
  'Radish',
  'Sugarcane',
  'Cotton',
  'Turmeric',
  'Grapes',
  'Banana',
  'Mango',
  'Orange',
  'Pomegranate',
  'Papaya',
  'Guava',
  'Custard Apple',
  'Sweet Lime',
  'Coconut',
];

// Irrigation Types
export const IRRIGATION_TYPES = ['Drip', 'Flood', 'Sprinkler', 'Rainfed'];
