/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FarmerSubmission {
  'farmerId' : string,
  'responses' : string,
  'fieldCoordinates' : string,
  'fieldCoordinatesList' : [] | [Array<string>],
  'redeemedNFTId' : string,
  'claimedSTMileage' : [] | [bigint],
  'fieldImagePath' : string,
  'reviewCompleted' : boolean,
  'selectedSTValue' : string,
  'currentCrop' : string,
  'state' : string,
  'nftId' : string,
  'deviceId' : string,
  'oldRandomArrayBooleansArray' : [] | [Array<boolean>],
  'adminReviewStatus' : string,
  'pictureId' : string,
  'fieldSize' : string,
  'location' : string,
  'previousCrop' : string,
  'reqCount' : [] | [bigint],
  'nftIdAdjustedBooleansArray' : [] | [Array<boolean>],
  'responsesArray' : [] | [Array<string>],
  'oldRandomArray' : [] | [Array<bigint>],
}
export interface UserProfile { 'name' : string, 'loginId' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSubmission' : ActorMethod<[bigint, FarmerSubmission], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllSubmissions' : ActorMethod<[], Array<FarmerSubmission>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSubmission' : ActorMethod<[bigint], [] | [FarmerSubmission]>,
  'getSubmissionsByDevice' : ActorMethod<[string], Array<FarmerSubmission>>,
  'getSubmissionsByFarmer' : ActorMethod<[string], Array<FarmerSubmission>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];