/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FarmerSubmission = IDL.Record({
  'farmerId' : IDL.Text,
  'responses' : IDL.Text,
  'fieldCoordinates' : IDL.Text,
  'fieldCoordinatesList' : IDL.Opt(IDL.Vec(IDL.Text)),
  'redeemedNFTId' : IDL.Text,
  'claimedSTMileage' : IDL.Opt(IDL.Nat),
  'fieldImagePath' : IDL.Text,
  'reviewCompleted' : IDL.Bool,
  'selectedSTValue' : IDL.Text,
  'currentCrop' : IDL.Text,
  'state' : IDL.Text,
  'nftId' : IDL.Text,
  'deviceId' : IDL.Text,
  'oldRandomArrayBooleansArray' : IDL.Opt(IDL.Vec(IDL.Bool)),
  'adminReviewStatus' : IDL.Text,
  'pictureId' : IDL.Text,
  'fieldSize' : IDL.Text,
  'location' : IDL.Text,
  'previousCrop' : IDL.Text,
  'reqCount' : IDL.Opt(IDL.Nat),
  'nftIdAdjustedBooleansArray' : IDL.Opt(IDL.Vec(IDL.Bool)),
  'responsesArray' : IDL.Opt(IDL.Vec(IDL.Text)),
  'oldRandomArray' : IDL.Opt(IDL.Vec(IDL.Nat)),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'loginId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSubmission' : IDL.Func([IDL.Nat, FarmerSubmission], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(FarmerSubmission)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSubmission' : IDL.Func([IDL.Nat], [IDL.Opt(FarmerSubmission)], ['query']),
  'getSubmissionsByDevice' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FarmerSubmission)],
      ['query'],
    ),
  'getSubmissionsByFarmer' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FarmerSubmission)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FarmerSubmission = IDL.Record({
    'farmerId' : IDL.Text,
    'responses' : IDL.Text,
    'fieldCoordinates' : IDL.Text,
    'fieldCoordinatesList' : IDL.Opt(IDL.Vec(IDL.Text)),
    'redeemedNFTId' : IDL.Text,
    'claimedSTMileage' : IDL.Opt(IDL.Nat),
    'fieldImagePath' : IDL.Text,
    'reviewCompleted' : IDL.Bool,
    'selectedSTValue' : IDL.Text,
    'currentCrop' : IDL.Text,
    'state' : IDL.Text,
    'nftId' : IDL.Text,
    'deviceId' : IDL.Text,
    'oldRandomArrayBooleansArray' : IDL.Opt(IDL.Vec(IDL.Bool)),
    'adminReviewStatus' : IDL.Text,
    'pictureId' : IDL.Text,
    'fieldSize' : IDL.Text,
    'location' : IDL.Text,
    'previousCrop' : IDL.Text,
    'reqCount' : IDL.Opt(IDL.Nat),
    'nftIdAdjustedBooleansArray' : IDL.Opt(IDL.Vec(IDL.Bool)),
    'responsesArray' : IDL.Opt(IDL.Vec(IDL.Text)),
    'oldRandomArray' : IDL.Opt(IDL.Vec(IDL.Nat)),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'loginId' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSubmission' : IDL.Func([IDL.Nat, FarmerSubmission], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(FarmerSubmission)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSubmission' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(FarmerSubmission)],
        ['query'],
      ),
    'getSubmissionsByDevice' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FarmerSubmission)],
        ['query'],
      ),
    'getSubmissionsByFarmer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FarmerSubmission)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };