/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FarmerSubmission {
    farmerId: string;
    responses: string;
    fieldCoordinates: string;
    fieldCoordinatesList?: Array<string>;
    redeemedNFTId: string;
    claimedSTMileage?: bigint;
    fieldImagePath: string;
    reviewCompleted: boolean;
    selectedSTValue: string;
    currentCrop: string;
    state: string;
    nftId: string;
    deviceId: string;
    oldRandomArrayBooleansArray?: Array<boolean>;
    adminReviewStatus: string;
    pictureId: string;
    fieldSize: string;
    location: string;
    previousCrop: string;
    reqCount?: bigint;
    nftIdAdjustedBooleansArray?: Array<boolean>;
    responsesArray?: Array<string>;
    oldRandomArray?: Array<bigint>;
}
export interface UserProfile {
    name: string;
    loginId: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addSubmission(submissionId: bigint, submission: FarmerSubmission): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllSubmissions(): Promise<Array<FarmerSubmission>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getSubmission(submissionId: bigint): Promise<FarmerSubmission | null>;
    getSubmissionsByDevice(deviceId: string): Promise<Array<FarmerSubmission>>;
    getSubmissionsByFarmer(farmerId: string): Promise<Array<FarmerSubmission>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { FarmerSubmission as _FarmerSubmission, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addSubmission(arg0: bigint, arg1: FarmerSubmission): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubmission(arg0, to_candid_FarmerSubmission_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubmission(arg0, to_candid_FarmerSubmission_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllSubmissions(): Promise<Array<FarmerSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissions();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissions();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmission(arg0: bigint): Promise<FarmerSubmission | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmission(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmission(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmissionsByDevice(arg0: string): Promise<Array<FarmerSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionsByDevice(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionsByDevice(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmissionsByFarmer(arg0: string): Promise<Array<FarmerSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionsByFarmer(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionsByFarmer(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_FarmerSubmission_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FarmerSubmission): FarmerSubmission {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<boolean>]): Array<boolean> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<bigint>]): Array<bigint> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FarmerSubmission]): FarmerSubmission | null {
    return value.length === 0 ? null : from_candid_FarmerSubmission_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    farmerId: string;
    responses: string;
    fieldCoordinates: string;
    fieldCoordinatesList: [] | [Array<string>];
    redeemedNFTId: string;
    claimedSTMileage: [] | [bigint];
    fieldImagePath: string;
    reviewCompleted: boolean;
    selectedSTValue: string;
    currentCrop: string;
    state: string;
    nftId: string;
    deviceId: string;
    oldRandomArrayBooleansArray: [] | [Array<boolean>];
    adminReviewStatus: string;
    pictureId: string;
    fieldSize: string;
    location: string;
    previousCrop: string;
    reqCount: [] | [bigint];
    nftIdAdjustedBooleansArray: [] | [Array<boolean>];
    responsesArray: [] | [Array<string>];
    oldRandomArray: [] | [Array<bigint>];
}): {
    farmerId: string;
    responses: string;
    fieldCoordinates: string;
    fieldCoordinatesList?: Array<string>;
    redeemedNFTId: string;
    claimedSTMileage?: bigint;
    fieldImagePath: string;
    reviewCompleted: boolean;
    selectedSTValue: string;
    currentCrop: string;
    state: string;
    nftId: string;
    deviceId: string;
    oldRandomArrayBooleansArray?: Array<boolean>;
    adminReviewStatus: string;
    pictureId: string;
    fieldSize: string;
    location: string;
    previousCrop: string;
    reqCount?: bigint;
    nftIdAdjustedBooleansArray?: Array<boolean>;
    responsesArray?: Array<string>;
    oldRandomArray?: Array<bigint>;
} {
    return {
        farmerId: value.farmerId,
        responses: value.responses,
        fieldCoordinates: value.fieldCoordinates,
        fieldCoordinatesList: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.fieldCoordinatesList)),
        redeemedNFTId: value.redeemedNFTId,
        claimedSTMileage: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.claimedSTMileage)),
        fieldImagePath: value.fieldImagePath,
        reviewCompleted: value.reviewCompleted,
        selectedSTValue: value.selectedSTValue,
        currentCrop: value.currentCrop,
        state: value.state,
        nftId: value.nftId,
        deviceId: value.deviceId,
        oldRandomArrayBooleansArray: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.oldRandomArrayBooleansArray)),
        adminReviewStatus: value.adminReviewStatus,
        pictureId: value.pictureId,
        fieldSize: value.fieldSize,
        location: value.location,
        previousCrop: value.previousCrop,
        reqCount: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.reqCount)),
        nftIdAdjustedBooleansArray: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.nftIdAdjustedBooleansArray)),
        responsesArray: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.responsesArray)),
        oldRandomArray: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.oldRandomArray))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FarmerSubmission>): Array<FarmerSubmission> {
    return value.map((x)=>from_candid_FarmerSubmission_n6(_uploadFile, _downloadFile, x));
}
function to_candid_FarmerSubmission_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FarmerSubmission): _FarmerSubmission {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    farmerId: string;
    responses: string;
    fieldCoordinates: string;
    fieldCoordinatesList?: Array<string>;
    redeemedNFTId: string;
    claimedSTMileage?: bigint;
    fieldImagePath: string;
    reviewCompleted: boolean;
    selectedSTValue: string;
    currentCrop: string;
    state: string;
    nftId: string;
    deviceId: string;
    oldRandomArrayBooleansArray?: Array<boolean>;
    adminReviewStatus: string;
    pictureId: string;
    fieldSize: string;
    location: string;
    previousCrop: string;
    reqCount?: bigint;
    nftIdAdjustedBooleansArray?: Array<boolean>;
    responsesArray?: Array<string>;
    oldRandomArray?: Array<bigint>;
}): {
    farmerId: string;
    responses: string;
    fieldCoordinates: string;
    fieldCoordinatesList: [] | [Array<string>];
    redeemedNFTId: string;
    claimedSTMileage: [] | [bigint];
    fieldImagePath: string;
    reviewCompleted: boolean;
    selectedSTValue: string;
    currentCrop: string;
    state: string;
    nftId: string;
    deviceId: string;
    oldRandomArrayBooleansArray: [] | [Array<boolean>];
    adminReviewStatus: string;
    pictureId: string;
    fieldSize: string;
    location: string;
    previousCrop: string;
    reqCount: [] | [bigint];
    nftIdAdjustedBooleansArray: [] | [Array<boolean>];
    responsesArray: [] | [Array<string>];
    oldRandomArray: [] | [Array<bigint>];
} {
    return {
        farmerId: value.farmerId,
        responses: value.responses,
        fieldCoordinates: value.fieldCoordinates,
        fieldCoordinatesList: value.fieldCoordinatesList ? candid_some(value.fieldCoordinatesList) : candid_none(),
        redeemedNFTId: value.redeemedNFTId,
        claimedSTMileage: value.claimedSTMileage ? candid_some(value.claimedSTMileage) : candid_none(),
        fieldImagePath: value.fieldImagePath,
        reviewCompleted: value.reviewCompleted,
        selectedSTValue: value.selectedSTValue,
        currentCrop: value.currentCrop,
        state: value.state,
        nftId: value.nftId,
        deviceId: value.deviceId,
        oldRandomArrayBooleansArray: value.oldRandomArrayBooleansArray ? candid_some(value.oldRandomArrayBooleansArray) : candid_none(),
        adminReviewStatus: value.adminReviewStatus,
        pictureId: value.pictureId,
        fieldSize: value.fieldSize,
        location: value.location,
        previousCrop: value.previousCrop,
        reqCount: value.reqCount ? candid_some(value.reqCount) : candid_none(),
        nftIdAdjustedBooleansArray: value.nftIdAdjustedBooleansArray ? candid_some(value.nftIdAdjustedBooleansArray) : candid_none(),
        responsesArray: value.responsesArray ? candid_some(value.responsesArray) : candid_none(),
        oldRandomArray: value.oldRandomArray ? candid_some(value.oldRandomArray) : candid_none()
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
